namespace Ninja_Price.Enums
{
    public enum ItemTypes
    {
        None,
        Currency,
        DivinationCard,
        Essence,
        Fragment,
        Prophecy,
        UniqueAccessory,
        UniqueArmour,
        UniqueFlask,
        UniqueJewel,
        UniqueMap,
        UniqueWeapon,
        Map,
        Resonator,
        Fossil,
        Scarab,
        Incubator,
        Oil,
        Catalyst,
        DeliriumOrbs,
        Vials,
        MavenInvitation,
        Artifact
    }
}